import type { WasteCategory } from "@/lib/types";

export const wasteCategories: WasteCategory[] = [
  {
    id: "plastic",
    name: "Plastic",
    color: "#3b82f6",
    icon: "🧴",
    description: "Common household plastics such as bottles, containers, and wraps.",
    recyclingMethod: "Rinse, dry, and place in your plastics recycling stream.",
    materialInfo: "Usually PET, HDPE, PVC, or mixed plastic resin.",
  },
  {
    id: "glass",
    name: "Glass",
    color: "#14b8a6",
    icon: "🥃",
    description: "Bottles and jars made from glass packaging.",
    recyclingMethod: "Rinse and place in glass recycling.",
    materialInfo: "Generally recyclable if it is clean and unbroken.",
  },
  {
    id: "paper",
    name: "Paper",
    color: "#f59e0b",
    icon: "📄",
    description: "Newspaper, office paper, and clean paper packaging.",
    recyclingMethod: "Keep dry and recycle into paper streams.",
    materialInfo: "Paper fibers are commonly repulped for new paper products.",
  },
  {
    id: "cardboard",
    name: "Cardboard",
    color: "#a16207",
    icon: "📦",
    description: "Corrugated boxes and carton-based materials.",
    recyclingMethod: "Flatten and keep cardboard dry.",
    materialInfo: "Usually accepted in cardboard recycling where available.",
  },
  {
    id: "metal",
    name: "Metal",
    color: "#94a3b8",
    icon: "🥫",
    description: "Steel and tin containers and metal packaging.",
    recyclingMethod: "Rinse and place into metal recycling where accepted.",
    materialInfo: "Refers to ferrous or non-ferrous metal alloys.",
  },
  {
    id: "organic-waste",
    name: "Organic Waste",
    color: "#22c55e",
    icon: "🍏",
    description: "Food scraps, plant waste, and biodegradable organics.",
    recyclingMethod: "Compost if local systems allow.",
    materialInfo: "Bio-degradable material that can break down naturally.",
  },
  {
    id: "textile",
    name: "Textile",
    color: "#8b5cf6",
    icon: "🧥",
    description: "Clothes, bags, and fabric-based goods.",
    recyclingMethod: "Donate reusable pieces or use textile recycling bins.",
    materialInfo: "Cotton, polyester, or mixed fabric blends.",
  },
  {
    id: "e-waste",
    name: "E-Waste",
    color: "#ef4444",
    icon: "🔌",
    description: "Discarded electronic devices and accessories.",
    recyclingMethod: "Take to certified e-waste collection points.",
    materialInfo: "Contains batteries, circuit boards, and small electronic parts.",
  },
  {
    id: "battery",
    name: "Battery",
    color: "#f97316",
    icon: "🔋",
    description: "Buttons, lithium-ion, and portable battery cells.",
    recyclingMethod: "Use dedicated battery recycling drop-off.",
    materialInfo: "Requires special handling due to chemical and fire risks.",
  },
  {
    id: "food-waste",
    name: "Food Waste",
    color: "#84cc16",
    icon: "🥗",
    description: "Perishable food and leftovers that should not contaminate recycling.",
    recyclingMethod: "Separate to organics or municipal food waste channels.",
    materialInfo: "Often contaminated with oils or moisture.",
  },
  {
    id: "aluminum-can",
    name: "Aluminium Can",
    color: "#64748b",
    icon: "🥤",
    description: "Soda and drink cans made from aluminum.",
    recyclingMethod: "Crush or flatten when practical and place in metal recycling.",
    materialInfo: "Often a high-value, easily recyclable packaging stream.",
  },
  {
    id: "pet-bottle",
    name: "PET Bottle",
    color: "#60a5fa",
    icon: "🍼",
    description: "Clear plastic beverage bottles with high recyclability.",
    recyclingMethod: "Empty and rinse before placing in plastic recycling.",
    materialInfo: "Polyethylene terephthalate (PET) resin code 1.",
  },
  {
    id: "hdpe-plastic",
    name: "HDPE Plastic",
    color: "#0ea5e9",
    icon: "🧪",
    description: "Milk jugs, detergent bottles, and other high-density plastics.",
    recyclingMethod: "Rinse and recycle in the plastic stream.",
    materialInfo: "High-density polyethylene resin code 2.",
  },
  {
    id: "pvc",
    name: "PVC",
    color: "#f43f5e",
    icon: "🧰",
    description: "Rigid or flexible PVC products and piping.",
    recyclingMethod: "Check local guidance; some PVC is not accepted in curbside recycling.",
    materialInfo: "Polyvinyl chloride resin code 3 and often contamination-sensitive.",
  },
  {
    id: "tetra-pack",
    name: "Tetra Pack",
    color: "#fb7185",
    icon: "🧃",
    description: "Carton beverage and food packaging made from layered materials.",
    recyclingMethod: "Empty, rinse, and recycle via carton recovery channels.",
    materialInfo: "Layered paper, plastic, and aluminum composite packaging.",
  },
  {
    id: "others",
    name: "Others",
    color: "#6b7280",
    icon: "🗑️",
    description: "Items that do not fit the main categories.",
    recyclingMethod: "Follow local municipal waste rules or disposal guidance.",
    materialInfo: "Needs manual review due to mixed composition.",
  },
];
